name: offline_music_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.46
  audio_service: ^0.18.17
  audio_session: ^0.1.21
  
  # Local Files & Data
  on_audio_query: ^2.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  
  # UI & State
  provider: ^6.1.2
  rxdart: ^0.27.7
  cached_network_image: ^3.3.1
  device_info_plus: ^10.1.0
  mocktail: ^1.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/sample_songs/
    - assets/images/

